#!/bin/bash
############################
# setup
# originally sourced from 
# http://blog.smalleycreative.com/tutorials/using-git-and-github-to-manage-your-dotfiles/
# This script creates symlinks from the home directory to any dotfiles in ~/dotfiles
############################

dir="$( cd "$(dirname "$0")" ; pwd -P )"
#dir=~/dotfiles                    # dotfiles directory
backup=~/dotfiles_backup          # old dotfiles backup directory

# create the backup directory
echo "Creating $backup for backup of any existing dotfiles in ~"
mkdir -p $backup

# change to the dotfiles directory
cd $dir

# get the list of dotfiles
files=$(ls -xdfbB --file-type .*)

# one at time, backup the originals and copy the new from $dir to ~
echo "Creating symlinks from $dir to ~, moving backups along the way"
for file in $files; do
    if ! [[ $file =~ (([/=>@|])$)|(^.git) ]]
    then
        echo $file
        [[ -f ~/$file ]] && mv ~/$file $backup
        ln -s $dir/$file ~/$file
    fi
done

# make sure the submodules are up to date
git submodule update --init

# make some .vim subdirectories and set up vim-plug
mkdir -p ~/.vim/tmp
mkdir -p ~/.vim/autoload
ln -s $dir/vim-plug/plug.vim ~/.vim/autoload
